package:
  name: arduino-tools
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
   path: ..
   git_url: ..

build:
   number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
   script: python install_arduino_cli.py

outputs:
   - name: arduino-cli
     files:
      - bin
      - etc
      - data

requirements:
   build:
     - python
     - ripgrep

about:
   home: https://github.com/slaclab/arduino-tools
   summary: anaconda wrapper for arduino-cli
